export const ADD_BURGER_INGREDIENT_IN_CONSTRUCTOR: "ADD_BURGER_INGREDIENT_TO_CONSTRUCTOR" =
	"ADD_BURGER_INGREDIENT_TO_CONSTRUCTOR";
export const UPDATE_BURGER_BUN_IN_CONSTRUCTOR: "UPDATE_BURGER_BUN_IN_CONSTRUCTOR" =
	"UPDATE_BURGER_BUN_IN_CONSTRUCTOR";
export const REMOVE_BURGER_INGREDIENT_FROM_CONSTRUCTOR: "REMOVE_BURGER_INGREDIENT_FROM_CONSTRUCTOR" =
	"REMOVE_BURGER_INGREDIENT_FROM_CONSTRUCTOR";
export const CLEAR_BURGER_INGREDIENTS_FROM_CONSTRUCTOR: "CLEAR_BURGER_INGREDIENTS_FROM_CONSTRUCTOR" =
	"CLEAR_BURGER_INGREDIENTS_FROM_CONSTRUCTOR";


export const SET_ORDER_BURGER_INGREDIENTS_CONSTRUCTOR: "SET_ORDER_BURGER_INGREDIENTS" =
	"SET_ORDER_BURGER_INGREDIENTS";
